name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.39.1"

      - name: Compile executables
        run: |
          deno compile --output ./build/rwg-x86_64-unknown-linux-gnu --target x86_64-unknown-linux-gnu --allow-read main.ts
          deno compile --output ./build/rwg-x86_64-pc-windows-msvc --target x86_64-pc-windows-msvc --allow-read main.ts
          deno compile --output ./build/rwg-x86_64-apple-darwin --target x86_64-apple-darwin --allow-read main.ts
          deno compile --output ./build/rwg-aarch64-apple-darwin --target aarch64-apple-darwin --allow-read main.ts

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload executables to GitHub release
        uses: csexton/release-asset-action@v2
        with:
          pattern: "./build/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
